# SPDX-License-Identifier: MIT
- hosts: letsencrypt
  become: yes
  tags: letsencrypt
  tasks:
    - name: 'LetsEncrypt'
      import_role:
        name: roles/letsencrypt

- hosts: all
  become: yes
  tags: tileserver
  tasks:
    - name: 'Tile server (steps until data import)'
      import_role:
        name: roles/tileserver
    - name: 'Tile server (steps after data import)'
      import_role:
        name: roles/tileserver_step2

- hosts: all
  become: yes
  tags: website
  tasks:
    - name: 'Website and API'
      import_role:
        name: roles/website
      vars:
        osm_dbname: gis
        website_hostname: www.openrailwaymap.org
        website_hostname_aliases:
          - openrailwaymap.org
          - buegelfalte.openrailwaymap.org
        api_hostname: api.openrailwaymap.org
        website_dir: /var/www/www.openrailwaymap.org
        openrailwaymap_user_home: /srv/openrailwaymap
        api_v2:
          directory: /opt/OpenRailwayMap-api

- hosts: blog
  become: yes
  tags: blog
  tasks:
    - name: 'Blog'
      import_role:
        name: roles/blog
      vars:
        blog:
          hostname: blog.openrailwaymap.org
          hostname_aliases: []
          directory: /var/www/blog

- hosts: mailservers
  become: yes
  tags: mail
  tasks:
    - name: 'Mail server'
      import_role:
        name: roles/mail
      vars:
        mail:
          mailman2: false
          mailman3: true
          http_hostname: lists.openrailwaymap.org

- hosts: backup_access
  become: yes
  tags: backup
  tasks:
    - name: 'Prepare for backup access'
      import_role:
        name: roles/backup_access
      vars:
        backup_user_in_groups:
          - user: backup
            groups: list
        postgresql_backup_user:
          username: backup
          databases: ['mailman3web', 'mailman3']

- hosts: munin_nodes
  become: yes
  tags: munin
  tasks:
    - name: 'Munin node'
      import_role:
        name: roles/munin_node
