---
users:
  - name: michael
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf4xi+0ZDIBcVpdnM/B/zUKar0PQ17yx65eT9r7pmbpuaBKUcp5NV8bl/w1OSxPJkQYyICR1iKddEMMVwKGEhc48Aao24WnwIuuV4jmx+BfTSQ4qsW+zmLrF0/gmgLUFlx06ShIjFt4C7wlOy078PamwkHzzhA2gEETKqJqYKh/2nrCqa1h1RTOb8UJGOwUtHw0z+IXUI1C78eDz/lckPBt3C8K3s8plMqGHnl55S+C2x7EqXGZanVSCdlSwGlsi3Y3N1XJ/nAsaJPRkoUjxe7F9pY3IJSxLdGkp+XMbS3dZ5Y0Z99vOyH75EffJZqkkCwiJqHHJE+1cCC4MKepzQh michael@ackerMichael"
