- name: systemd restart tirex-backend-manager
  systemd:
    name: tirex-backend-manager
    state: restarted
- name: systemd restart tirex-master
  systemd:
    name: tirex-master
    state: restarted
- name: systemd reload tirex-backend-manager
  systemd:
    name: tirex-backend-manager
    state: reloaded
- name: systemd reload tirex-master
  systemd:
    name: tirex-master
    state: reloaded
- name: systemd restart delete_old_metatiles.timer
  systemd:
    name: delete_old_metatiles.timer
    state: restarted
