all:
  hosts:
    openrailwaymap2019.michreichert.de:
      ansible_user: root
  vars:
    ansible_python_interpreter: python3

  children:
    base:
      hosts:
        openrailwaymap2019.michreichert.de

    security:
      hosts:
        openrailwaymap2019.michreichert.de

    tileserver:
      hosts:
        openrailwaymap2019.michreichert.de:
      vars:
        osm_dbname: gis
        pg_version: 11
        tileserver_script_dir: /opt/OpenRailwayMap-server-config
        osm_data_dir: /nvme/data/planet
        flatnodes_dir: /nvme/data/flatnodes
        tile_expiry_dir: /nvme/data/tileupdate
        cartocss_dir: /opt/OpenRailwayMap-CartoCSS
