all:
  hosts:
    buegelfalte.openrailwaymap.org:
      ansible_user: root
      apache2_logdir: /var/log/apache2
  vars:
    ansible_python_interpreter: python3

  children:
    base:
      hosts:
        buegelfalte.openrailwaymap.org

    security:
      hosts:
        buegelfalte.openrailwaymap.org

    letsencrypt:
      hosts:
        buegelfalte.openrailwaymap.org
      vars:
        ssl_domain: openrailwaymap.org
        certificate_alt_names: 'DNS:buegelfalte.openrailwaymap.org,DNS:openrailwaymap.org,DNS:www.openrailwaymap.org,DNS:tiles.openrailwaymap.org,DNS:a.tiles.openrailwaymap.org,DNS:b.tiles.openrailwaymap.org,DNS:c.tiles.openrailwaymap.org,DNS:api.openrailwaymap.org,DNS:blog.openrailwaymap.org'

    tileserver:
      hosts:
        buegelfalte.openrailwaymap.org:
      vars:
        osm_dbname: gis
        pg_version: 11
        tileserver_script_dir: /opt/OpenRailwayMap-server-config
        osm_data_dir: /nvme/data/planet
        flatnodes_dir: /nvme/data/flatnodes
        tile_expiry_dir: /nvme/data/tileupdate
        cartocss_dir: /opt/OpenRailwayMap-CartoCSS
        website_hostname: www.openrailwaymap.org
        website_hostname_aliases:
          - openrailwaymap.org
          - buegelfalte.openrailwaymap.org
        api_hostname: api.openrailwaymap.org
        website_dir: /var/www/www.openrailwaymap.org
        openrailwaymap_user_home: /srv/openrailwaymap

    blog:
      hosts:
        buegelfalte.openrailwaymap.org:
          blog:
            hostname: blog.openrailwaymap.org
            hostname_aliases: []
            directory: /var/www/blog

    munin_node:
      hosts:
        buegelfalte.openrailwaymap.org:
          ssl_domain: openrailwaymap.org
          accept_from: ['148.251.245.55', '2a01:4f8:192:81b6::2']
      vars:
        # Do not mention ip_ here, it is handled separately.
        munin_node_plugins:
          - {name: apache_accesses, dest: apache_accesses}
          - {name: apache_processes, dest: apache_processes}
          - {name: apache_volume, dest: apache_volume}
        munin_node_ip_plugin: true
