name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          override-deps: ansible-lint>=5.3.2
          targets: "ansible/roles/*/tasks/*.yml ./ansible/group_vars/*.yml ansible/*.yml"
